version: 1.0.0
services:
  - name: go-demo-4
    envs:
      - name: go-demo-4-uat
        addr: uat.go-demo-4.192.168.0.10.nip.io
      - name: go-demo-4-prod
        addr: go-demo-4.192.168.0.10.nip.io